### ISSUE TITLE
18.06分支报错

### ISSUE THREAD

**Issue by 281677160** [immortalwrt/immortalwrt#284] opened 2021-02-16 15:54 UTC
* pkg_hash_fetch_best_installation_candidate: Packages for libreadline8 found, but incompatible with the architectures configured
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-app-autoupdate:
 * 	libncursesw6
 * opkg_install_cmd: Cannot install package luci-app-autoupdate.
 * pkg_hash_fetch_best_installation_candidate: Packages for fdisk found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package fdisk.
make[2]: *** [package/Makefile:68: package/install] Error 255

一直编译都没问题的，早上还编译也没问题的，晚上编译就报错了，请问一下 这个怎么处理，感谢！

**Comment by 1715173329** [comment] 2021-02-16 15:55
This is a duplicate of #283.

**Comment by 281677160** [comment] 2021-02-16 15:59
感谢回复，那就只能等了，定时更新这个插件不编译看看能成功不

**Comment by xiaobaishu1** [comment] 2021-02-17 10:18
> This is a duplicate of #283.

![image](https://user-images.githubusercontent.com/53339509/108190150-8a7f8c00-714c-11eb-9afa-b64b58c5fcab.png)

**Closed** 2021-02-17 10:21 UTC
Labels: duplicate
