### ISSUE TITLE
最近一次的更新，云编译失败

### ISSUE THREAD

**Issue by SakuraFallingMad** [immortalwrt/immortalwrt#837] opened 2022-12-11 12:20 UTC
![image](https://user-images.githubusercontent.com/31793080/206903135-1d10420e-05d9-4948-9965-f2d6e8a20cb9.png)
![image](https://user-images.githubusercontent.com/31793080/206903168-7955075c-2e80-4d7e-bbc9-911cc8c67c6c.png)
本地编译发现tools/xz包有问题.
![image](https://user-images.githubusercontent.com/31793080/206903742-46246b5d-0332-43ca-95ef-c8528267b516.png)

**Comment by SakuraFallingMad** [comment] 2022-12-11 12:37
#838

**Comment by 1715173329** [comment] 2022-12-11 14:39
Duplicate of #838.

**Closed by 1715173329** 2022-12-11 14:39 UTC
